name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd /tmp
            rm -rf stefanoscalfari.it
            git clone https://github.com/Vorshim92/stefanoscalfari.it.git
            cd stefanoscalfari.it
            ./server_deploy.sh
